### PR TITLE
Fix preprocessor errors for some statements

### PR DESCRIPTION
**Pull request by kiendang**
due to not being supported by variable inspector

The same error with `Import`s in #763 occurs with object, class and type too, basically everything that's not a val, var, def or expression so just disable variable inspector for them for now.

```scala
object Object

cmd1.sc:7: not found: value res1
  .declareVariable("res1", res1); Iterator() }, 
                           ^Compilation Failed

Compilation Failed
```

### CODE REVIEW

**Review by alexarchambault — APPROVED** [review]
Thanks @kiendang!

(I was under the impression that I had fixed related issues some time ago, but I might be wrong, or I must not have pushed it…)

**Comment by alexarchambault** [comment]
The CI errors might be caused by our use of outdated sbt launchers. Having a look.

**Comment by alexarchambault** [comment]
@kiendang In order to fix the CI issues here, I merged https://github.com/almond-sh/almond/pull/756, which switches the build to [mill](https://github.com/com-lihaoyi/mill). 

I put some useful mill commands in [this file](https://github.com/almond-sh/almond/blob/master/docs/pages/dev-from-sources.md), and https://github.com/almond-sh/almond/pull/800 adds more details for IDEs.

If you're having an issue with mill, please do tell me. I don't want it to be a hindrance to you, and any issue you run into could be worth mentioning in the doc above.

**Comment by kiendang** [comment]
Thanks for the heads-up. I'll take a look and let you know.

**Pull request merged**
