### PR TITLE
Rework API / helpers to display stuff (WIP)

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
cc @sbrunk (this touches and may touch more some of your image-related code)

**Comment by sbrunk** [comment]
I've been thinking about using something builder pattern like myself to make this more user friendly and avoid users to use options in args. So :+1:

**Comment by alexarchambault** [comment]
@sbrunk The last commit may break some image-related code in notebooks. In particular, `Image.fromArray` went away (one should just call `Image(…)` instead), and `Image.fromUrl` and `Image.fromFile` only accept one argument (extra stuff must be passed with builder-pattern calls, like `.withWidth(…)`, etc.)

Also, simply calling `html(…)` or `markdown(…)` doesn't return a handle to update things anymore. (One should use `Html(…)` or `Markdown(…)`, then use builder pattern calls, and call `update` on them.)

**Comment by alexarchambault** [comment]
Optionally, the former API could be kept, and enabled if a flag is passed to the kernel…

**Comment by alexarchambault** [comment]
(Planning to document that on the website before merging…)

**Comment by sbrunk** [comment]
In the examples repo there are only three occurrences of `Image` or so that need to be changed. It's also not part of the documentation (except ScalaDoc) so far, so at least what concerning these changes I'm not sure if we need to keep the old API. Perhaps migration notes are enough.

The plotly-almond module needs to be updated for sure.

**Comment by alexarchambault** [comment]
Yes, I think I'll go ahead and scrap the old API, then. All the more that the former API (as a whole) is kind of messy compared to the new one, IMO.

**Comment by alexarchambault** [comment]
Included in https://github.com/almond-sh/almond/pull/353.

**Pull request closed without merging**
