### PR TITLE
Allow to run a metabrowse server along the scala kernel for source navigation

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by alexarchambault** [comment]
To address:
- [ ] metadoc server not published for scala 2.11
- [ ] possible issues with metadoc in 2.12.6
- [ ] metadoc depends on fastparse 1.x, newer Ammonite versions on fastparse 2.x

**Comment by alexarchambault** [comment]
cc @olafurpg

**Comment by olafurpg** [comment]
The fastparse incompatibility should be fixed by https://github.com/scalameta/scalameta/pull/1801, I hope to have a new scalameta release out within the next week (we still have a few java 11 issues I'd like to fix).

**Comment by aishfenton** [comment]
What would the user interaction be to trigger this? Alt-Click on a definition in a notebook cell ?

**Comment by alexarchambault** [comment]
@aishfenton In a (very) first time, this should be a link from the inspection window (shift-tab in jupyter classic). Clicking on the link will either open a new window (if none were previously opened), or change the address of a previously opened one.

We can later discuss more refined ways of using that (hover or other), which should likely need some development on the front-end side.

**Comment by alexarchambault** [comment]
Now consistently getting errors like
```none
ERROR MessageHandler$ Error while processing inspect_request message
java.lang.AssertionError: assertion failed:
  Race condition detected: You are running a presentation compiler method outside the PC thread.[phase: <no phase>] Please file a ticket with the current stack trace at https://www.assembla.com/spaces/scala-ide/support/tickets
     while compiling: Current.sc
        during phase: globalPhase=<no phase>, enteringPhase=typer
     library version: version 2.12.7
    compiler version: version 2.12.7
  reconstructed args: -Ymacro-expand:discard -nowarn -Yresolve-term-conflict:object

  last tree to typer: This(object InspectWrapper)
       tree position: line 7 of Current.sc
            tree tpe: InspectWrapper.type
              symbol: object InspectWrapper
   symbol definition: class InspectWrapper extends AnyRef (a ModuleClassSymbol)
      symbol package: <empty>
       symbol owners: object InspectWrapper
           call site: <none> in <none>

== Source file context for tree position ==

     4
     5 object InspectWrapper{
     6 Thread.currentThread
     7 }
     8
  scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:163)
  scala.tools.nsc.interactive.Global.assertCorrectThread(Global.scala:525)
  scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1609)
  scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1540)
  metabrowse.server.MetabrowseServer.$anonfun$urlForSymbol$1(MetabrowseServer.scala:101)
  metabrowse.server.MetabrowseServer.$anonfun$urlForSymbol$1$adapted(MetabrowseServer.scala:94)
  scala.collection.immutable.List.foreach(List.scala:388)
  metabrowse.server.MetabrowseServer.urlForSymbol(MetabrowseServer.scala:94)
  almond.ScalaInterpreter.$anonfun$inspect$1(ScalaInterpreter.scala:604)
```

Looking into it…

**Comment by alexarchambault** [comment]
Note to self, or to anyone interested to test that branch locally. Steps to run this branch, once it's checked out:
```
$ sbt publishLocal
$ SCALA_VERSION=2.12.7 ALMOND_VERSION=0.1.12-SNAPSHOT
$ coursier bootstrap \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    -o almond-snapshot --embed-files=false \
    --sources --default=true
$ ./almond-snapshot --install \
    --id scala-snapshot \
    --display-name "Scala (snapshot)" \
    --force \
    --log debug \
    --log-to "$HOME/almond-snapshot-logs.txt" \
    --metadoc
```

Ensure you have the latest coursier launcher (`coursier --help` should print a version >= `1.1.0-M9` - that's for the `--default` option, to generate a launcher with both standard JARs and source JARs).

**Pull request merged**
