### PR TITLE
Vega only

### PR DESCRIPTION
**Pull request by Quafadas**
This sets up a couple of default handlers which pipe the correct mime types to display Vega / Lite charts in output cells. 

Further update the docs with links to plotly scala, and how to use Vega/lite from Almond.

### CODE REVIEW

**Comment by Quafadas** [comment]
Sadly don't understand the CI messages... defeated! I'll keep an eye out for a passing CI and revisit then.

**Comment by sideeffffect** [comment]
Maybe you need to increase Java's stack size: `-Xss8M`?

**Comment by Quafadas** [comment]
@sideeffffect hey cool, thanks!

**Comment by Quafadas** [comment]
@alexarchambault As I think you may be looking at almond at the moment…  would you consider looking at this  pr?

**Review by alexarchambault — COMMENTED** [review]
Thanks for opening this, @Quafadas!

I'm a bit reluctant to add some library-specific classes in the `jupyter-api` module itself… This module is supposed to only expose somehow "core" APIs. But this could live in a separate module (or even in a separate repo), that users would load via an `import $ivy` (and it would be fine mentioning that module in the Almond documentation).

**Pull request closed without merging**
