### PR TITLE
Update metabrowse to 0.2.8

### LINKED ISSUE #764: Error starting metabrowse server
Currently if `metabrowse` is enabled, attempting to get contextual help of a symbol (shift-tab) would result in a kernel restart due to failure to start the metabrowse server. Happens both with Scala 2.12.10 and 2.13.1.

```
java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    scala/meta/internal/mtags/MtagsEnrichments.scala$meta$internal$mtags$MtagsEnrichments$$filenameToLanguage(Ljava/lang/String;)Lscala/meta/internal/semanticdb/Language; @33: ar
eturn
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'scala/meta/internal/semanticdb/Language' (from method signature)
  Current Frame:
    bci: @33
    flags: { }
    locals: { 'scala/meta/internal/mtags/MtagsEnrichments', 'java/lang/String' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: 2b12 74b6 007a 9900 09b2 007e a700 152b
    0000010: 1280 b600 7a99 0009 b200 83a7 0006 b200
    0000020: 86b0
  Stackmap Table:
    same_frame(@15)
    same_frame(@30)
    same_locals_1_stack_item_frame(@33,Object[#4])

        at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$addSourceJar$2(OnDemandSymbolIndex.scala:56)
        at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$addSourceJar$2$adapted(OnDemandSymbolIndex.scala:55)
        at scala.meta.internal.io.PlatformFileIO$.withJarFileSystem(PlatformFileIO.scala:87)
        at scala.meta.internal.io.FileIO$.withJarFileSystem(FileIO.scala:44)
        at scala.meta.internal.mtags.OnDemandSymbolIndex.$anonfun$addSourceJar$1(OnDemandSymbolIndex.scala:55)
        at scala.meta.internal.mtags.OnDemandSymbolIndex.tryRun(OnDemandSymbolIndex.scala:107)
        at scala.meta.internal.mtags.OnDemandSymbolIndex.addSourceJar(OnDemandSymbolIndex.scala:54)
        at metabrowse.server.MetabrowseServer.$anonfun$replaceClasspath$2(MetabrowseServer.scala:79)
        at metabrowse.server.MetabrowseServer.$anonfun$replaceClasspath$2$adapted(MetabrowseServer.scala:79)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at metabrowse.server.MetabrowseServer.replaceClasspath(MetabrowseServer.scala:79)
        at metabrowse.server.MetabrowseServer.start(MetabrowseServer.scala:48)
        at almond.internals.ScalaInterpreterInspections.createMetabrowseServer(ScalaInterpreterInspections.scala:105)
        at almond.internals.ScalaInterpreterInspections.$anonfun$metabrowseServerOpt$2(ScalaInterpreterInspections.scala:40)
        at scala.Option.orElse(Option.scala:447)
        at almond.internals.ScalaInterpreterInspections.$anonfun$metabrowseServerOpt$1(ScalaInterpreterInspections.scala:39)
        at scala.Option.orElse(Option.scala:447)
        at almond.internals.ScalaInterpreterInspections.metabrowseServerOpt(ScalaInterpreterInspections.scala:38)
        at almond.internals.ScalaInterpreterInspections.inspect(ScalaInterpreterInspections.scala:111)
        at almond.ScalaInterpreter.inspect(ScalaInterpreter.scala:151)
        at almond.interpreter.Interpreter.inspect(Interpreter.scala:146)
        at almond.interpreter.Interpreter.inspect$(Interpreter.scala:145)
        at almond.ScalaInterpreter.inspect(ScalaInterpreter.scala:21)
        at almond.interpreter.util.AsyncInterpreterOps.asyncInspect(AsyncInterpreterOps.scala:21)
        at almond.interpreter.util.AsyncInterpreterOps.asyncInspect$(AsyncInterpreterOps.scala:20)
        at almond.ScalaInterpreter.asyncInspect(ScalaInterpreter.scala:21)
        at almond.ScalaInterpreter.asyncInspect(ScalaInterpreter.scala:21)
        at almond.interpreter.InterpreterToIOInterpreter.$anonfun$inspectionCancellable$4(InterpreterToIOInterpreter.scala:139)
        at almond.interpreter.util.Cancellable.run(Cancellable.scala:32)
        at almond.interpreter.InterpreterToIOInterpreter.inspect(InterpreterToIOInterpreter.scala:150)
        at almond.interpreter.messagehandlers.InterpreterMessageHandlers.$anonfun$inspectHandler$1(InterpreterMessageHandlers.scala:147)
        at almond.interpreter.messagehandlers.MessageHandler$.$anonfun$blocking$2(MessageHandler.scala:127)
        at almond.interpreter.messagehandlers.MessageHandler$.$anonfun$blockingTaskStream$1(MessageHandler.scala:157)
        at cats.effect.IO$Map.apply(IO.scala:1699)
        at cats.effect.IO$Map.apply(IO.scala:1697)
        at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:187)
        at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:463)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:484)
        at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:422)
        at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

### PR DESCRIPTION
**Pull request by kiendang**
Attempt to update `metabrowse` to 0.2.6

Close #764

steps to run

```sh
./mill -i all "__.publishLocal"

SCALA_VERSION="2.13.6" ALMOND_VERSION="0.11.2-47-434d403c-SNAPSHOT"

coursier bootstrap \
  sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
  -M almond.ScalaKernel --embed-files=false \
  -r central -r ivy2local -r jitpack \
  --default=true --sources -o almond -f

./almond --install \
  --id almond-snapshot_$SCALA_VERSION --display-name "Scala $SCALA_VERSION (snapshot)" \
  --force \
  --log debug \
  --log-to "$HOME/log.txt" \
  --metabrowse yes
```

might need to tee the log to another file, *e.g* `tail -f "$HOME/log.txt" > "$HOME/log-retain.txt"` because when `almond` crashes the log got deleted.

Currently kind of works for Scala 2.12 but still runs into this issue similar to https://github.com/almond-sh/almond/pull/246#issuecomment-443251725. Did you solve this earlier @alexarchambault?

```
Exception in thread "main" java.lang.AssertionError: assertion failed:
  Race condition detected: You are running a presentation compiler method outside the PC thread.[phase: <no phase>] Please file a ticket with the current stack trace at https://w
ww.assembla.com/spaces/scala-ide/support/tickets
     while compiling: Current.sc
        during phase: globalPhase=<no phase>, enteringPhase=parser
     library version: version 2.12.15
    compiler version: version 2.12.15
  reconstructed args: -nowarn -Xmaxwarns 0 -Yresolve-term-conflict:object -Ymacro-expand:discard

  last tree to typer: Literal(Constant(()))
       tree position: line 5 of Current.sc
            tree tpe: Unit
              symbol: null
           call site: <none> in <none>

== Source file context for tree position ==

     2   x
     3 }
     4
     5 object InspectWrapper{
     6 val x = 2
     7 }
     8
        at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:185)
        at scala.tools.nsc.interactive.Global.assertCorrectThread(Global.scala:533)
        at scala.reflect.internal.Symbols$Symbol.transformInfos(Symbols.scala:1653)
        at scala.reflect.internal.Symbols$Symbol.rawInfo(Symbols.scala:1642)
```

Doesn't work for Scala 2.13

```
Exception in thread "main" jar:file:///home/kien/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/pprint_3/0.6.6/pprint_3-0.6.6-sources.jar!/TPrintImpl.scala:15: error
: unclosed character literal
      '{ $expr + $other }
      ^
        at scala.meta.internal.tokenizers.Reporter.syntaxError(Reporter.scala:23)
        at scala.meta.internal.tokenizers.Reporter.syntaxError$(Reporter.scala:23)
        at scala.meta.internal.tokenizers.Reporter$$anon$1.syntaxError(Reporter.scala:33)
```

Looks like some of the Scala 3 source jars got included. Checked the log and those are `fansi`, `pprint`, `sourcecode` and `scala3-library`.

TODO
- include `metabrowse` for all Scala versions, without the need for `scala-has-metabrowse`/`scala-has-metabrowse` and manually specifying.
- add `--metabrowse-port` cli option to manually specify a port for metabrowse

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks for opening this @kiendang. To address the issue you're seeing, it should now be possible to depend on metabrowse via "full cross version scala suffix", like `org.scalameta:::metabrowse-server:0.2.6`. This should workaround the Scala version mismatch issues.

We should also be able to get rid of the metabrowse available or not code. Thanks to this full cross scala version, metabrowse should work with all scala versions now.

**Comment by alexarchambault** [comment]
I should be able to have a closer look at this if needed in the coming days.

**Comment by alexarchambault** [comment]
Merging this, thanks again @kiendang!

**Comment by kiendang** [comment]
I still consistently ran into the "You are running a presentation compiler method outside the PC thread" error though. Probably the problem is with metabrowse coz I don't remember getting that bug in #779 where I took out metabrowse and implemented inspection with mtags directly.

**Pull request merged**
