### PR TITLE
Comm Enhancements

### PR DESCRIPTION
**Pull request by sbrunk**
ipywidgets sets its protocol version in the metadata of the comm messages it sends.

This is an attempt to support setting metadata for comm messages. Sending comm messages also throws exceptions now if data or metadata can't be parsed into JSON objects (it was a TODO before in `DefaultCommHandler`).

### CODE REVIEW

**Comment by sbrunk** [comment]
Is there a way to run compile or test for all major Scala Versions with a single command? I've stumbled twice upon this. I.e. because almond-spark is disabled for 2.13 and `Either.toTry` isn't in 2.11.

**Comment by sbrunk** [comment]
mima complains because of the changes in `CommHandler`. 

I.e.
```
abstract method commOpen(java.lang.String,java.lang.String,java.lang.String)Unit in class almond.interpreter.api.CommHandler does not have a correspondent in current version
```
But even if I keep the original `commOpen` and add an overloaded variant with the `metadata` arg, it doesn't seem to be binary compatible:
```
abstract method commOpen(java.lang.String,java.lang.String,java.lang.String,java.lang.String)Unit in class almond.interpreter.api.CommHandler is present only in current version
```

The `sender` method also has a default parameter value, so we can't overload it to add a `metadata` parameter.

**Comment by alexarchambault** [comment]
To make mima happier, the new `comm*` methods should be put in a new abstract class extending the current one (like `ExtendedCommHandler`). And where these methods are called, we should check if we have an `ExtendedCommHandler` instance, and call the new methods if that's the case. For the `sender` method, I guess an overload, with no default values, should be added along the current one.

But overall, I'm not sure preserving binary compatibility is worth the hassle… Versions up to `0.6.0` could just be filtered out around [here](https://github.com/almond-sh/almond/blob/4c79ef8dcbeab7b6dea1e79981a047af9579fd25/project/Mima.scala#L19).

**Comment by alexarchambault** [comment]
> Is there a way to run compile or test for all major Scala Versions with a single command?

`+test` or `+test:compile` ought to work, to

**Comment by sbrunk** [comment]
I'm working on a fix #384 which brings in even more changes to `CommHandler`. So I'd be in favor of breaking binary compatibility.

These changes touch the `sender` method too so If it's OK for you I'd rename this PR to "Comm enhancements" and add these changes in the same branch.

**Comment by alexarchambault** [comment]
@sbrunk Go ahead!

**Comment by sbrunk** [comment]
Seems like I have to filter out all versions manually in https://github.com/almond-sh/almond/blob/4c79ef8dcbeab7b6dea1e79981a047af9579fd25/project/Mima.scala#L19 for mima to be happy.

Would it make sense to increase the version here to 0.6.0?
https://github.com/almond-sh/almond/blob/b711f116759c393f94e63febbac0bab99977496a/project/Settings.scala#L216-L218

**Comment by sbrunk** [comment]
I've also added the changes related to #384 in e942f3b8fa8b84ea67c753ad5b992122caa739f8

**Comment by alexarchambault** [comment]
@sbrunk Should this be merged?

**Comment by sbrunk** [comment]
Yes this should be enough to fix #384

**Comment by alexarchambault** [comment]
Let's merge then! It would have been nice to have non regression tests for that, but we can always add those later…

**Pull request merged**
