### PR TITLE
revert to cmd for the wrapper name

### PR DESCRIPTION
**Pull request by coreyoconnor**
This is the name expected by Spark.

### CODE REVIEW

**Review by alexarchambault — COMMENTED** [review]
Thanks @coreyoconnor!

Going to merge to fix things in the short term (as soon as the CI is green). Ideally, I'd love to have that fixed by customizing the `CodeClassWrapper` in Ammonite (maybe opening its API a bit in the Ammonite code base, then using that from Almond), so that the `org.apache.spark.sql.catalyst.encoders.OuterScopes.addOuterScope(this)` calls are automatically added in the cells as soon as we detect that Spark is loaded (and maybe something can be done manually for the cells ran before loading Spark).

Also, it seems tests such as [those](https://github.com/alexarchambault/ammonite-spark/blob/db96780c0894a040d3eadce363e17289825cd4c9/modules/tests/src/main/scala/ammonite/spark/SparkReplTests.scala#L235-L253) (provided we remove the manual `addOuterScope` call in it) would have caught that issue. It'd be great to run such tests in the integration tests of Almond too (I guess by re-using [the scripts that ammonite-spark uses](https://github.com/alexarchambault/ammonite-spark/blob/db96780c0894a040d3eadce363e17289825cd4c9/.github/scripts/test.sh#L10-L17), adding almond-spark during the tests, and copying the inputs of the tests here).

If you feel like it, don't hesitate to try to take a cut at that. I might do it at some point later, else.

**Comment by coreyoconnor** [comment]
sounds good! I might have some time to devote. I'll post a draft-PR for extending the integration tests if I get started.

Adding the link to similar code in spark for future reference: https://github.com/apache/spark/blob/master/connector/connect/client/jvm/src/main/scala/org/apache/spark/sql/application/ConnectRepl.scala#L116

**Comment by coreyoconnor** [comment]
I'm able to reproduce the integration test failures locally. Will update the PR shortly.

**Review by alexarchambault — APPROVED** [review]
Merging, thanks @coreyoconnor!

**Pull request merged**
